field: 684d693e-cbfd-47a4-ace8-7518bbf5bb2e
fieldLayouts:
  f5982a5c-41c5-424c-a60b-1aab22f7794b:
    tabs:
      -
        elements:
          -
            fieldUid: 81cc139c-25ba-4eef-b7ad-c41ac00f4290
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 50f638bd-8243-4d02-b031-ab5132f95dda
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 04e31b20-d2db-44f4-ad54-623b2796fb3c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 1433b915-9d03-4b13-a136-236e007dd1cf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bee5e3f6-e139-4f97-88e1-48debc910742
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1e54690d-2eaf-412e-94bf-f78de6751332
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  04e31b20-d2db-44f4-ad54-623b2796fb3c:
    contentColumnType: string
    fieldGroup: null
    handle: ctaColor
    instructions: ''
    name: Color
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Clear
            -
              - value
              - none
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Education (green)'
            -
              - value
              - moss
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Celebration (pink)'
            -
              - value
              - watermelon
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Donate (purple)'
            -
              - value
              - indigo
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Uplifting (yellow)'
            -
              - value
              - canary
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  1433b915-9d03-4b13-a136-236e007dd1cf:
    contentColumnType: string
    fieldGroup: null
    handle: linkedEntry
    instructions: 'If you want to link to an entry/page on this site, use this option to choose the entry you want to link to, otherwise fill out the URL field for external links or files (PDFs).'
    name: Entry/Page
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Choose an entry'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  1e54690d-2eaf-412e-94bf-f78de6751332:
    contentColumnType: string(255)
    fieldGroup: null
    handle: ctaUrl
    instructions: 'Fill this field out only to link to external sites.'
    name: 'External Link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  50f638bd-8243-4d02-b031-ab5132f95dda:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  81cc139c-25ba-4eef-b7ad-c41ac00f4290:
    contentColumnType: text
    fieldGroup: null
    handle: intro
    instructions: ''
    name: Intro
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  bee5e3f6-e139-4f97-88e1-48debc910742:
    contentColumnType: string
    fieldGroup: null
    handle: linkedFile
    instructions: 'Choose from the site assets to link to a file, like a PDF.'
    name: File
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:fb4388de-0651-490b-95c1-88eb974f8ee0'
      defaultUploadLocationSubpath: '{owner.slug}'
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Choose a file'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fb4388de-0651-490b-95c1-88eb974f8ee0'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: cta
name: CTA
sortOrder: 3
