field: 684d693e-cbfd-47a4-ace8-7518bbf5bb2e
fieldLayouts:
  58937b4d-e508-4142-92cc-803372af32b9:
    tabs:
      -
        elements:
          -
            fieldUid: 9e40824a-64b1-449e-9434-07f092cd4cfc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb6ca250-6012-40f4-8c9f-765f561177cc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9e40824a-64b1-449e-9434-07f092cd4cfc:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image/Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:fb4388de-0651-490b-95c1-88eb974f8ee0'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:fb4388de-0651-490b-95c1-88eb974f8ee0'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fb6ca250-6012-40f4-8c9f-765f561177cc:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: image
name: Image/Video
sortOrder: 2
