field: 684d693e-cbfd-47a4-ace8-7518bbf5bb2e
fieldLayouts:
  889a2a29-49b9-4fb0-a918-6d0bd15d7ba4:
    tabs:
      -
        elements:
          -
            fieldUid: 1aeb7fc8-f6fb-4555-abea-9189eed36148
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 6c3c7fc2-6d2c-4078-8d1e-8384a136a804
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 8ffc7831-795d-48d4-afcf-a3a97baa6844
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6eca23cc-4365-4935-8d0f-5336cc43b017
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1aeb7fc8-f6fb-4555-abea-9189eed36148:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6c3c7fc2-6d2c-4078-8d1e-8384a136a804:
    contentColumnType: string
    fieldGroup: null
    handle: headlineStyle
    instructions: ''
    name: 'Headline Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  6eca23cc-4365-4935-8d0f-5336cc43b017:
    contentColumnType: text
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: false
    settings:
      addRowLabel: 'Add a button'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - URL
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - Color
                -
                  - handle
                  - color
                -
                  - width
                  - ''
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - 'Education (green)'
                        -
                          - value
                          - moss
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'Celebration (pink)'
                        -
                          - value
                          - watermelon
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'Donate (purple)'
                        -
                          - value
                          - indigo
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'Uplifting (yellow)'
                        -
                          - value
                          - canary
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Clear
                        -
                          - value
                          - clear
                        -
                          - default
                          - false
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - Arrow
                -
                  - handle
                  - arrow
                -
                  - width
                  - ''
                -
                  - type
                  - lightswitch
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  8ffc7831-795d-48d4-afcf-a3a97baa6844:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 1
