fieldLayouts:
  9c34e089-0216-424c-8e78-2281c6f3b35e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: donors
hasUrls: true
name: Donors
settings:
  path: uploads/donors/
sortOrder: 4
type: craft\volumes\Local
url: '@rootUrl/uploads/donors/'
