contentColumnType: text
fieldGroup: 091254fe-3649-468b-b0c0-dea5e758d1ea
handle: artists
instructions: ''
name: Artists
searchable: false
settings:
  addRowLabel: 'Add artist'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Name
            -
              - handle
              - name
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'URL (optional)'
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - url
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
