contentColumnType: boolean
fieldGroup: 4a414505-7a6a-42dd-bec2-2b270c9a8f89
handle: contactLink
instructions: 'Show a link to contact page for event'
name: 'Contact Link'
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
