contentColumnType: integer(10)
fieldGroup: 4a414505-7a6a-42dd-bec2-2b270c9a8f89
handle: eventbriteId
instructions: ''
name: 'Eventbrite ID'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
