contentColumnType: string
fieldGroup: 4e0276a9-c8ed-48a8-abf9-8e26731faa39
handle: eventsOptions
instructions: ''
name: 'Events Options'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 33b4bfef-5100-4d10-9b95-9912e5db2d7b
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 52a76be3-a678-4b60-86a8-4ed843edfe31
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_eventsoptions}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
