contentColumnType: string
fieldGroup: 4e0276a9-c8ed-48a8-abf9-8e26731faa39
handle: eventsOptions
instructions: ''
name: 'Events Options'
searchable: false
settings:
  contentTable: '{{%stc_eventsoptions}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
