contentColumnType: string
fieldGroup: 4e0276a9-c8ed-48a8-abf9-8e26731faa39
handle: globalShareImage
instructions: 'Default share image used for pages with no inherent shareable image'
name: 'Global Share Image'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:fb4388de-0651-490b-95c1-88eb974f8ee0'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:fb4388de-0651-490b-95c1-88eb974f8ee0'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
