contentColumnType: boolean
fieldGroup: 4a414505-7a6a-42dd-bec2-2b270c9a8f89
handle: multiSession
instructions: ''
name: Multi-Session
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
