contentColumnType: text
fieldGroup: 4a414505-7a6a-42dd-bec2-2b270c9a8f89
handle: recurringDay
instructions: 'Specify which day a multi-session event lands on'
name: 'Recurring Day'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'e.g. Fridays or Weekdays'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
