contentColumnType: string(640)
fieldGroup: 4c4fecfd-904c-4971-a20a-1732a6d7ebe7
handle: seoDescription
instructions: 'Used for meta description to improve SEO'
name: 'SEO Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 160
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
