dateModified: 1601587226
email:
  fromEmail: nate@firebellydesign.com
  fromName: Lubeznik
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  admin-bar:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form-extensions:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  diy-widget:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  incognito-field:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  lubeznik:
    edition: standard
    enabled: true
    schemaVersion: '1.0'
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  single-cat:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
system:
  edition: solo
  live: true
  name: Lubeznik
  schemaVersion: 3.5.13
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
