field: f4a75c9a-905d-4ba9-b271-2e172fba3026
fieldLayouts:
  5eb94eb8-46dd-470a-b61c-8576387680d2:
    tabs:
      -
        elements:
          -
            fieldUid: 91de6c14-2755-4ef7-9341-0bad68938cef
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 21e27589-6235-4564-8c7e-bd809eda464a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 58c6bb65-fb2c-4cff-982a-444486c92a3f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 17988ba5-4095-4d9e-8847-99be78e1c0d0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  17988ba5-4095-4d9e-8847-99be78e1c0d0:
    contentColumnType: string(255)
    fieldGroup: null
    handle: squareUrl
    instructions: ''
    name: 'Square URL'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  21e27589-6235-4564-8c7e-bd809eda464a:
    contentColumnType: text
    fieldGroup: null
    handle: cost
    instructions: "\r\n"
    name: Cost
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  58c6bb65-fb2c-4cff-982a-444486c92a3f:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  91de6c14-2755-4ef7-9341-0bad68938cef:
    contentColumnType: text
    fieldGroup: null
    handle: tierTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
