field: 0e6d989a-b96f-48a0-84da-60cc248179f4
fieldLayouts:
  4da37bc9-51f1-4ee9-9850-084d328b937d:
    tabs:
      -
        elements:
          -
            fieldUid: 33b4bfef-5100-4d10-9b95-9912e5db2d7b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 52a76be3-a678-4b60-86a8-4ed843edfe31
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  33b4bfef-5100-4d10-9b95-9912e5db2d7b:
    contentColumnType: string(255)
    fieldGroup: null
    handle: eventsArchiveUrl
    instructions: 'Where "View Archive" links to on Events page'
    name: 'Events Archive URL'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  52a76be3-a678-4b60-86a8-4ed843edfe31:
    contentColumnType: string(255)
    fieldGroup: null
    handle: learningArchiveUrl
    instructions: 'Where "View Archive" links to on Learning page'
    name: 'Learning Archive URL'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
