field: de3546d8-a9df-4236-aff3-57b6dd49ef50
fieldLayouts:
  4e133f86-59dc-4efb-978c-38673a1c1d7f:
    tabs:
      -
        elements:
          -
            fieldUid: 52be1378-4dfc-4eb6-8ee2-1ce85ca7434d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3bb35385-15df-43f5-a98e-2f0fc2306070
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5645c3fc-f293-4daf-bd93-917c859ed501
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e64a82b5-fc63-4cc1-9a85-dc30fa5c6cb8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3bb35385-15df-43f5-a98e-2f0fc2306070:
    contentColumnType: text
    fieldGroup: null
    handle: personTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  52be1378-4dfc-4eb6-8ee2-1ce85ca7434d:
    contentColumnType: text
    fieldGroup: null
    handle: personName
    instructions: ''
    name: Name
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5645c3fc-f293-4daf-bd93-917c859ed501:
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: ''
    name: Email
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e64a82b5-fc63-4cc1-9a85-dc30fa5c6cb8:
    contentColumnType: text
    fieldGroup: null
    handle: phone
    instructions: ''
    name: Phone
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
