fieldLayouts:
  326d5b83-92d6-49d6-bcbe-bceea67eebb2:
    tabs:
      -
        elements:
          -
            fieldUid: da162a7b-a07b-45b3-a63e-304cbcfeaee2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc7adfd1-edb8-4bd2-b852-68ff5ebf23af
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Site Options'
        sortOrder: 1
handle: siteOptions
name: 'Site Options'
