enableVersioning: true
handle: donate
name: Donate
propagationMethod: all
siteSettings:
  9a48f731-32a4-4cc5-b916-86836bf6609c:
    enabledByDefault: true
    hasUrls: true
    template: donate/index
    uriFormat: donate
type: single
