enableVersioning: true
handle: exhibitions
name: Exhibitions
propagationMethod: all
siteSettings:
  9a48f731-32a4-4cc5-b916-86836bf6609c:
    enabledByDefault: true
    hasUrls: true
    template: exhibitions/index
    uriFormat: exhibitions
type: single
