enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  9a48f731-32a4-4cc5-b916-86836bf6609c:
    enabledByDefault: true
    hasUrls: true
    template: homepage/index
    uriFormat: __home__
type: single
