enableVersioning: true
handle: learning
name: Learning
propagationMethod: all
siteSettings:
  9a48f731-32a4-4cc5-b916-86836bf6609c:
    enabledByDefault: true
    hasUrls: true
    template: learning/index
    uriFormat: learning
type: single
