enableVersioning: true
handle: membership
name: Membership
propagationMethod: all
siteSettings:
  9a48f731-32a4-4cc5-b916-86836bf6609c:
    enabledByDefault: true
    hasUrls: true
    template: membership/index
    uriFormat: membership
type: single
