enableVersioning: true
handle: outreach
name: Outreach
propagationMethod: all
siteSettings:
  9a48f731-32a4-4cc5-b916-86836bf6609c:
    enabledByDefault: true
    hasUrls: true
    template: outreach/index
    uriFormat: outreach
type: single
